// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using NicoPasino.Core.Modelos.Movies;

namespace NicoPasino.Infra.Data;

public partial class moviesdbContext : DbContext
{
    public moviesdbContext(DbContextOptions<moviesdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Genre> Genre { get; set; }

    public virtual DbSet<Movie> Movie { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Genre>(entity =>
        {
            entity.ToTable("genre");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.ToTable("movie");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IdPublica).HasColumnName("idPublica");
            entity.Property(e => e.Activo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_movie_activo")
                .HasColumnName("activo");
            entity.Property(e => e.Director)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("director");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.FechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("fechaCreacion");
            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("fechaModificacion");
            entity.Property(e => e.Poster)
                .HasColumnType("text")
                .HasColumnName("poster");
            entity.Property(e => e.Rate)
                .HasColumnType("decimal(2, 1)")
                .HasColumnName("rate");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("title");
            entity.Property(e => e.Year).HasColumnName("year");

            entity.HasMany(d => d.Genre).WithMany(p => p.Movie)
                .UsingEntity<Dictionary<string, object>>(
                    "MovieGenres",
                    r => r.HasOne<Genre>().WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__movie_gen__genre__2B3F6F97"),
                    l => l.HasOne<Movie>().WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__movie_gen__movie__2A4B4B5E"),
                    j =>
                    {
                        j.HasKey("MovieId", "GenreId").HasName("PK__movie_ge__B249DF9D6711EEA6");
                        j.ToTable("movieGenres");
                        j.IndexerProperty<int>("MovieId").HasColumnName("movieId");
                        j.IndexerProperty<int>("GenreId").HasColumnName("genreId");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}