// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using NicoPasino.Core.Modelos.Notas;

namespace NicoPasino.Infra.Data;

public partial class notasdbContext : DbContext
{
    public notasdbContext(DbContextOptions<notasdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cards> Cards { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Cards>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("cards");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("color");
            entity.Property(e => e.Fecha)
                .HasMaxLength(50)
                .HasColumnName("fecha");
            entity.Property(e => e.Header)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("header");
            entity.Property(e => e.Hora)
                .HasColumnType("time")
                .HasColumnName("hora");
            entity.Property(e => e.IdPublica).HasColumnName("idPublica");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Text)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("text");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}