// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NicoPasino.Core.Modelos.Ventas;

public partial class Venta
{
    public int Id { get; set; }

    public int IdCliente { get; set; }

    public decimal PrecioTotal { get; set; }

    public DateTime? FechaVenta { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual ICollection<Ventaporproducto> Ventaporproducto { get; set; } = new List<Ventaporproducto>();
}