// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NicoPasino.Core.Modelos.Movies;

public partial class Movie
{
    public int Id { get; set; }

    public int? IdPublica { get; set; }

    public string Title { get; set; }

    public int Year { get; set; }

    public string Director { get; set; }

    public int Duration { get; set; }

    public string Poster { get; set; }

    public decimal Rate { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Genre> Genre { get; set; } = new List<Genre>();
}